toastygm/HarnMaster-3-FoundryVTT

css/hm3.css
module/actor/actor.js
module/actor/character-sheet.js
module/actor/creature-sheet.js
module/config.js
module/hm3.js
module/item/item-sheet.js
module/item/item.js
module/migrations.js
module/settings.js
scss/components/_combat.scss
scss/components/_forms.scss
scss/components/_gear.scss
scss/components/_items.scss
system.json
template.json
templates/actor/character-limited.html
templates/actor/character-sheet.html
templates/actor/creature-limited.html
templates/actor/creature-sheet.html
templates/item/armorgear-sheet.html

1. Support Drag/Drop of Items onto Characters
2. Calculation and effect of missile weight
3. Support for filling out armor locations from armor gear
4. Implemented initial system migration (still in progress)
5. Support "Carried" and "Equipped" toggles on gear, armor, weapons, and missiles
6. Support for "limited view" on creatures

Prepare for Release v0.5.0

---

module/actor/actor.js
system.json

Fixed defect in calculation of missile weight
Fixed defect in calculation of total weight (now limited to two decimal places)

Prepare for v0.5.2

---

module/actor/actor.js
module/actor/base-actor-sheet.js
module/config.js
module/item/item-sheet.js
module/utility.js
system.json
templates/actor/character-sheet.html

Resolves #15, Resolves #16, resolves #18, resolves #19, resolves #20, resolves #21, resolves #22

Prepare for v0.6.3

---

module/actor/base-actor-sheet.js
module/utility.js
templates/actor/creature-sheet.html

Fix creature sheet skills and skill names

---

module/actor/actor.js
system.json

Prepare for 0.6.6

---

module/actor/actor.js

Reverted armorLocation init to original

---

css/hm3.css
module/actor/actor.js
module/actor/base-actor-sheet.js
scss/components/_tabs.scss
system.json
templates/actor/character-sheet.html
templates/chat/injury-card.html
templates/item/skill-sheet.html

Resolved #33, resolved #38, resolved #39, resolved #40

Prepare for v0.6.9

---

css/hm3.css
module/actor/actor.js
module/actor/base-actor-sheet.js
module/dice-hm3.js
module/hm3.js
module/migrations.js
scss/components/_skills.scss
scss/components/_spell.scss
system.json
template.json
templates/actor/character-sheet.html
templates/dialog/item-qty.html
templates/item/armorgear-sheet.html

Resolved #47, resolved #48, resolved #44

Prepare for 0.7.0

---

css/hm3.css
module/actor/base-actor-sheet.js
scss/components/_items.scss
system.json
templates/actor/character-sheet.html

New Features:
* When a new Skill, Spell, Invocation, or Psionic Talent are dragged over to a character from another source, a dialog box pops up to allow you to fill in the details for the new item.  This does not occur for "inventory-type" items (such as weapons, armor, and misc gear), which simply get created.
Bugs Fixed:
* Resolved #67 Equip toggle not visible

Prepare for 0.7.3

---

css/hm3.css
module/actor/actor.js
module/actor/base-actor-sheet.js
module/config.js
module/dice-hm3.js
module/hm3.js
module/item/item.js
module/macros.js
module/migrations.js
scss/components/_combat.scss
scss/components/_spell.scss
system.json
template.json
templates/actor/character-limited.html
templates/actor/character-sheet.html
templates/actor/container-sheet.html
templates/actor/creature-limited.html
templates/actor/creature-sheet.html
templates/chat/damage-card.html
templates/chat/standard-test-card.html
templates/item/injury-sheet.html
templates/item/invocation-sheet.html
templates/item/missilegear-sheet.html
templates/item/psionic-sheet.html
templates/item/skill-sheet.html
templates/item/spell-sheet.html
templates/item/weapongear-sheet.html

Prepare for 0.7.4

---

module/actor/actor.js
module/actor/base-actor-sheet.js
module/hm3.js
module/migrations.js
system.json
template.json
templates/actor/character-sheet.html

Prepare for 0.7.5

---

css/hm3.css
module/actor/base-actor-sheet.js
module/actor/character-sheet.js
module/actor/container-sheet.js
module/actor/creature-sheet.js
module/config.js
module/utility.js
scss/components/_facade.scss
scss/components/_profile.scss
scss/hm3.scss
system.json
templates/actor/character-limited.html
templates/actor/character-sheet.html
templates/actor/container-limited.html
templates/actor/container-sheet.html
templates/actor/creature-limited.html
templates/actor/creature-sheet.html
templates/chat/esoteric-desc-card.html

New Features:
Resolved #150: Button on char sheet to output esoteric description to chat
Resolved #154: In gear/skill filter, search for text anywhere in name (not just at beginning)
Resolved #163: "Facade" view for all actors (what "limited" actors see)
Resolved #164: Sunsign as a drop-down

Prepare for 1.0.1

---

module/actor/actor.js
module/actor/base-actor-sheet.js
module/combat.js
module/dice-hm3.js
module/macros.js
module/settings.js
system.json
template.json
templates/actor/character-sheet.html
templates/chat/attack-card.html
templates/chat/missile-attack-card.html
templates/dialog/attack-dialog.html

Enhancements:
Resolved #148: Unequip weapons which fail WQ checks
Resolved #157: Missile Combat: range EML modifiers
Defects Fixed:
Resolved #176: FoundryVTT Config and Setup: Installation Failed: Not found
Resolved #174: bug: cannot initiate enhanced combat from token sheet
Resolved #172: bug: AQ isn't displayed on combat tab
Resolved #170: bug: AML dice roll on Missile weapons doesn't work
Resolved #168: Misspelling of "melee" on Combat tab of Actor sheet
Resolved #161: Combat Result: should result in Fumble roll?

Prepare for 1.0.2

---

css/hm3.css
module/actor/actor.js
module/actor/base-actor-sheet.js
module/combat.js
module/hm3.js
scss/global/_editor.scss
scss/hm3.scss
system.json

Fixed Defects
Resolved #220: Deleting container orphans contained items
Resolved #219: Automated Combat: defensive choice of block not displaying results
Resolved #218: Gear Tab: toggling carry button is not recalculating weight and PP correctly
Resolved #217: Stumble and Fumble not taking PP into account

Prepare for 1.1.2

---

module/actor/actor.js
system.json

Normalize dodge, initiative, and condition values
Fix auto armor calculation

Prepare for 1.2.10

---

module/actor/base-actor-sheet.js
module/combat.js
module/macros.js
module/migrations.js
system.json

Prepare for 1.2.11

---

module/actor/actor.js
module/actor/base-actor-sheet.js
module/config.js
module/dice-hm3.js
module/item/item-sheet.js
module/item/item.js
module/macros.js
module/migrations.js
module/settings.js
template.json
templates/actor/character-sheet.html
templates/actor/creature-sheet.html
templates/chat/missile-attack-card.html
templates/item/armorgear-sheet.html
templates/item/armorlocation-sheet.html
templates/item/injury-sheet.html
templates/item/missilegear-sheet.html
templates/item/weapongear-sheet.html

A comprehensive set of changed to remove support for HM Gold from the main system (support moved to the hm-gold module instead)

Remove gold mode

---

module/actor/actor.js
module/combat.js
module/hm3.js
system.json

Fixed #343 
Fixed #341 
Fixed #329

Prepare for 1.3.1

---

module/macros.js

Simple change to allow passing in a multiplier so it can be something other than 5

Option for multiplier

---

templates/actor/creature-sheet.html

Changed in creature sheet so Injury Level and Notes display correctly
(might need be done throughout the creature sheet)

Changed adata. to system.
